import Foundation

// MARK: - Generated Parser Data for JsonParser

// Generated by RezelCodeGen. DO NOT EDIT.

enum JsonParserData {
	static let version = 14

	static let states = "$bOVQPOOOOQO'#Cb'#CbOnQPO'#CeOvQPO'#ClOOQO'#Cr'#CrQOQPOOOOQO'#Cg'#CgO}QPO'#CfO!SQPO'#CtOOQO,59P,59PO![QPO,59PO!aQPO'#CuOOQO,59W,59WO!iQPO,59WOVQPO,59QOqQPO'#CmO!nQPO,59`OOQO1G.k1G.kOVQPO'#CnO!vQPO,59aOOQO1G.r1G.rOOQO1G.l1G.lOOQO,59X,59XOOQO-E6k-E6kOOQO,59Y,59YOOQO-E6l-E6l"

	static let stateData = "#O~OeOS~OQSORSOSSOTSOWQO_ROgPO~OVXOgUO~O^[O~PVO[^O~O]_OVhX~OVaO~O]bO^iX~O^dO~O]_OVha~O]bO^ia~O"

	static let goto = "!kjPPPPPPkPPkqwPPPPk{!RPPP!XP!e!hXSOR^bQWQRf_TVQ_Q`WRg`QcZRicQe^QTOQZRRhbRYQR]R"

	static let nodeNames = "⚠ JsonText True False Null Number String } { Object Property PropertyName : , ] [ Array"

	static let maxTerm = 25
	static let repeatNodeCount = 2

	static let nodePropNames: [String] = ["isolate", "openedBy", "closedBy"]

	static func buildNodeProps(_ extraProps: [String: NodePropBase] = [:]) -> [[Any]]? {
		let allProps = nodePropByName.merging(extraProps) { $1 }
		var result: [[Any]] = []
		if let prop = allProps["isolate"] {
			result.append([prop] as [Any] + [-2, 6, 11, ""])
		}
		if let prop = allProps["openedBy"] {
			result.append([prop] as [Any] + [14, "[", 7, "{"])
		}
		if let prop = allProps["closedBy"] {
			result.append([prop] as [Any] + [15, "]", 8, "}"])
		}
		return result.isEmpty ? nil : result
	}

	static let skippedNodes: [Int] = [0]

	static let tokenData = "(|~RaXY!WYZ!W]^!Wpq!Wrs!]|}$u}!O$z!Q!R%T!R![&c![!]&t!}#O&y#P#Q'O#Y#Z'T#b#c'r#h#i(Z#o#p(r#q#r(w~!]Oe~~!`Wpq!]qr!]rs!xs#O!]#O#P!}#P;'S!];'S;=`$o<%lO!]~!}Og~~#QXrs!]!P!Q!]#O#P!]#U#V!]#Y#Z!]#b#c!]#f#g!]#h#i!]#i#j#m~#pR!Q![#y!c!i#y#T#Z#y~#|R!Q![$V!c!i$V#T#Z$V~$YR!Q![$c!c!i$c#T#Z$c~$fR!Q![!]!c!i!]#T#Z!]~$rP;=`<%l!]~$zO]~~$}Q!Q!R%T!R![&c~%YRT~!O!P%c!g!h%w#X#Y%w~%fP!Q![%i~%nRT~!Q![%i!g!h%w#X#Y%w~%zR{|&T}!O&T!Q![&Z~&WP!Q![&Z~&`PT~!Q![&Z~&hST~!O!P%c!Q![&c!g!h%w#X#Y%w~&yO[~~'OO_~~'TO^~~'WP#T#U'Z~'^P#`#a'a~'dP#g#h'g~'jP#X#Y'm~'rOR~~'uP#i#j'x~'{P#`#a(O~(RP#`#a(U~(ZOS~~(^P#f#g(a~(dP#i#j(g~(jP#X#Y(m~(rOQ~~(wOW~~(|OV~"

	static let tokenPrec = 0

	static let topRules: [String: [Int]] = ["JsonText": [0, 1]]
	static let termNames: [Int: String] = [9: "Object", 10: "Property", 7: "\"}\"", 16: "Array", 24: "list<Property>", 15: "\"[\"", 11: "PropertyName", 2: "True", 18: "(\",\" value)+", 21: "whitespace", 4: "Null", 8: "\"{\"", 14: "\"]\"", 13: "\",\"", 25: "list<value>", 20: "%mainskip", 6: "String", 19: "␄", 17: "(\",\" Property)+", 0: "⚠", 5: "Number", 22: "value", 23: "string", 3: "False", 1: "@top", 12: "\":\""]
	nonisolated(unsafe) static var termTable: [String: Int] = Dictionary(termNames.map { ($1, $0) }, uniquingKeysWith: { a, _ in a })

	static func buildTokenizers(_: [String: TokenizerProtocol]) -> [Any] {
		var result: [Any] = []
		result.append(0)
		return result
	}

	static func makeSpec(
		externals: [String: TokenizerProtocol],
		specializedExternals _: [String: (String, Stack) -> Int] = [:],
		propSources: [NodePropSource]? = nil,
		context: ContextTracker? = nil
	) -> LRParser.ParserSpec {
		let tokenizers = Self.buildTokenizers(externals)

		return LRParser.ParserSpec(
			version: version,
			states: states,
			stateData: stateData,
			goto: goto,
			nodeNames: nodeNames,
			maxTerm: maxTerm,
			repeatNodeCount: repeatNodeCount,
			nodeProps: buildNodeProps(),
			propSources: propSources,
			skippedNodes: skippedNodes,
			tokenData: tokenData,
			tokenizers: tokenizers,
			topRules: topRules,
			context: context,
			tokenPrec: tokenPrec,
			termNames: termNames
		)
	}
}
