import Foundation
import Rezel

struct GrammarConfig: Codable {
	var grammarFile: String
	var outputVarName: String
	var externalTokenizers: [String]?
	var externalSpecializers: [String]?
	var contextTracker: Bool?
	var externalPropSources: [String]?
}

struct DummyTokenizer: TokenizerProtocol {
	var contextual: Bool = false
	var fallback: Bool = false
	var extend: Bool = false
	func token(_: Rezel.InputStream, stack _: Stack) {}
}

func escapeString(_ s: String) -> String {
	s.replacingOccurrences(of: "\\", with: "\\\\")
		.replacingOccurrences(of: "\"", with: "\\\"")
		.replacingOccurrences(of: "\n", with: "\\n")
		.replacingOccurrences(of: "\r", with: "\\r")
		.replacingOccurrences(of: "\t", with: "\\t")
}

func generateSwift(from serialized: SerializedParser, config: GrammarConfig) -> String {
	var lines: [String] = []
	lines.append("import Foundation")
	lines.append("")
	lines.append("// MARK: - Generated Parser Data for \(config.outputVarName)")
	lines.append("// Generated by RezelCodeGen. DO NOT EDIT.")
	lines.append("")

	lines.append("enum \(config.outputVarName)Data {")

	lines.append("    static let version = \(LrFile.Version)")
	lines.append("")
	lines.append("    static let states = \"\(escapeString(serialized.states))\"")
	lines.append("")
	lines.append("    static let stateData = \"\(escapeString(serialized.stateData))\"")
	lines.append("")
	lines.append("    static let goto = \"\(escapeString(serialized.goto))\"")
	lines.append("")
	lines.append("    static let nodeNames = \"\(escapeString(serialized.nodeNames))\"")
	lines.append("")
	lines.append("    static let maxTerm = \(serialized.maxTerm)")
	lines.append("    static let repeatNodeCount = \(serialized.repeatNodeCount)")

	if let names = serialized.nodePropNames, let data = serialized.nodePropData {
		lines.append("")
		lines.append("    static let nodePropNames: [String] = \(literalStringArray(names))")
		lines.append("")
		lines.append("    static func buildNodeProps(_ extraProps: [String: NodePropBase] = [:]) -> [[Any]]? {")
		lines.append("        let allProps = nodePropByName.merging(extraProps) { $1 }")
		lines.append("        var result: [[Any]] = []")
		for i in 0 ..< names.count {
			let propName = names[i]
			let terms = data[i]
			lines.append("        if let prop = allProps[\"\(propName)\"] {")
			lines.append("            result.append([prop] as [Any] + \(literalAnyArray(terms)))")
			lines.append("        }")
		}
		lines.append("        return result.isEmpty ? nil : result")
		lines.append("    }")
	}

	if let skipped = serialized.skippedNodes {
		lines.append("    static let skippedNodes: [Int] = \(skipped)")
	}

	lines.append("")
	lines.append("    static let tokenData = \"\(escapeString(serialized.tokenData))\"")

	lines.append("")
	lines.append("    static let tokenPrec = \(serialized.tokenPrec)")

	if let dialects = serialized.dialects {
		lines.append("    static let dialects: [String: Int] = \(literalStringIntDict(dialects))")
	}

	if let dp = serialized.dynamicPrecedences {
		lines.append("    static let dynamicPrecedences: [Int: Int] = \(literalIntIntDict(dp))")
	}

	lines.append("")
	lines.append("    static let topRules: [String: [Int]] = \(literalStringIntArrayDict(serialized.topRules))")

	if let tn = serialized.termNames {
		lines.append("    static let termNames: [Int: String] = \(literalIntStringDict(tn))")
		lines.append("    static nonisolated(unsafe) var termTable: [String: Int] = {")
		lines.append("        Dictionary(termNames.map { ($1, $0) }, uniquingKeysWith: { a, _ in a })")
		lines.append("    }()")
	}

	lines.append("")

	lines.append("    static func buildTokenizers(_ externals: [String: TokenizerProtocol]) -> [Any] {")
	lines.append("        var result: [Any] = []")
	for entry in serialized.tokenizerEntries {
		switch entry {
		case let .tokenGroup(id):
			lines.append("        result.append(\(id))")
		case let .localTokenGroup(data, precTable, elseToken):
			if let et = elseToken {
				lines.append("        result.append(LocalTokenGroup(data: \"\(escapeString(data))\", precTable: \(precTable), elseToken: \(et)))")
			} else {
				lines.append("        result.append(LocalTokenGroup(data: \"\(escapeString(data))\", precTable: \(precTable)))")
			}
		case let .external(name):
			lines.append("        result.append(externals[\"\(name)\"]!)")
		}
	}
	lines.append("        return result")
	lines.append("    }")

	if !serialized.specializedEntries.isEmpty {
		lines.append("")
		for entry in serialized.specializedEntries {
			if case let .table(term, table) = entry {
				let tableLiteral = literalStringIntDict(table)
				lines.append("    static let specTable_\(term): [String: Int] = \(tableLiteral)")
			}
		}
		lines.append("")
		lines.append("    static func buildSpecialized(_ externalSpecs: [String: (String, Stack) -> Int]) -> [LRParser.SpecializerSpec]? {")
		lines.append("        var result: [LRParser.SpecializerSpec] = []")
		for entry in serialized.specializedEntries {
			switch entry {
			case let .table(term, _):
				lines.append("        result.append(LRParser.SpecializerSpec(term: \(term), get: { value, _ in specTable_\(term)[String(value)] ?? -1 }, external: nil as ((String, Stack) -> Int)?, extend: false))")
			case let .external(term, name):
				lines.append("        result.append(LRParser.SpecializerSpec(term: \(term), get: { value, stack in externalSpecs[\"\(name)\"]?(String(value), stack) ?? -1 }, external: externalSpecs[\"\(name)\"], extend: false))")
			}
		}
		lines.append("        return result")
		lines.append("    }")
	}

	lines.append("")

	lines.append("    static func makeSpec(")
	lines.append("        externals: [String: TokenizerProtocol],")
	lines.append("        specializedExternals: [String: (String, Stack) -> Int] = [:],")
	lines.append("        propSources: [NodePropSource]? = nil,")
	lines.append("        context: ContextTracker? = nil")
	lines.append("    ) -> LRParser.ParserSpec {")
	lines.append("")
	lines.append("        let tokenizers = Self.buildTokenizers(externals)")
	lines.append("")
	lines.append("        return LRParser.ParserSpec(")
	lines.append("            version: version,")
	lines.append("            states: states,")
	lines.append("            stateData: stateData,")
	lines.append("            goto: goto,")
	lines.append("            nodeNames: nodeNames,")
	lines.append("            maxTerm: maxTerm,")
	lines.append("            repeatNodeCount: repeatNodeCount,")
	if serialized.nodePropNames != nil {
		lines.append("            nodeProps: buildNodeProps(),")
	}
	lines.append("            propSources: propSources,")
	if let _ = serialized.skippedNodes {
		lines.append("            skippedNodes: skippedNodes,")
	}
	lines.append("            tokenData: tokenData,")
	lines.append("            tokenizers: tokenizers,")
	lines.append("            topRules: topRules,")
	lines.append("            context: context,")
	if serialized.dialects != nil {
		lines.append("            dialects: dialects,")
	}
	if serialized.dynamicPrecedences != nil {
		lines.append("            dynamicPrecedences: dynamicPrecedences,")
	}
	if !serialized.specializedEntries.isEmpty {
		lines.append("            specialized: buildSpecialized(specializedExternals),")
	}
	lines.append("            tokenPrec: tokenPrec,")
	if serialized.termNames != nil {
		lines.append("            termNames: termNames")
	}
	lines.append("        )")
	lines.append("    }")

	lines.append("}")
	return lines.joined(separator: "\n")
}

func literalStringArray(_ arr: [String]) -> String {
	let items = arr.map { "\"\(escapeString($0))\"" }.joined(separator: ", ")
	return "[\(items)]"
}

func literalAnyArray(_ arr: [Any]) -> String {
	let items = arr.map { item -> String in
		if let i = item as? Int { return "\(i)" }
		if let s = item as? String { return "\"\(escapeString(s))\"" }
		return "nil"
	}.joined(separator: ", ")
	return "[\(items)]"
}

func literalStringIntDict(_ dict: [String: Int]) -> String {
	let items = dict.map { "\"\(escapeString($0))\": \($1)" }.joined(separator: ", ")
	return "[\(items)]"
}

func literalIntIntDict(_ dict: [Int: Int]) -> String {
	let items = dict.map { "\($0): \($1)" }.joined(separator: ", ")
	return "[\(items)]"
}

func literalStringIntArrayDict(_ dict: [String: [Int]]) -> String {
	let items = dict.map { "\"\(escapeString($0))\": \($1)" }.joined(separator: ", ")
	return "[\(items)]"
}

func literalIntStringDict(_ dict: [Int: String]) -> String {
	let items = dict.map { "\($0): \"\(escapeString($1))\"" }.joined(separator: ", ")
	return "[\(items)]"
}

func main() throws {
	let args = CommandLine.arguments
	guard args.count >= 4 else {
		print("Usage: RezelCodeGen <grammar-file> <config-file> <output-file>")
		exit(1)
	}

	let grammarPath = args[1]
	let configPath = args[2]
	let outputPath = args[3]

	let grammarText = try String(contentsOfFile: grammarPath, encoding: .utf8)
	let configData = try Data(contentsOf: URL(fileURLWithPath: configPath))
	let config = try JSONDecoder().decode(GrammarConfig.self, from: configData)

	let stubTokenizer: (String, [String: Int]) -> TokenizerProtocol = { _, _ in DummyTokenizer() }

	let serialized = try buildSerializedParser(grammarText, options: BuildOptions(
		externalTokenizer: stubTokenizer
	))

	let swiftCode = generateSwift(from: serialized, config: config)
	try swiftCode.write(toFile: outputPath, atomically: true, encoding: .utf8)
	print("Generated \(outputPath)")
}

try main()
